# config.make generated by configure script
POCO_CONFIG = Android
POCO_BASE = /home/gangheok/opensource/Poco/Poco/poco-1.6.1
POCO_BUILD = /home/gangheok/opensource/Poco/Poco/poco-1.6.1
POCO_PREFIX = /usr/local
POCO_FLAGS = 
OMIT = CppUnit CppParser CodeGeneration PageCompiler Remoting Data/MySQL Data/ODBC Zip XML
LINKMODE = STATIC
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
export LINKMODE
