/* WARNING!!! THIS IS AUTO-GENERATED FILE!!! DO NOT MODIFY IT MANUALLY!!! */
/* GENERATED BY: /home/crystax/work/ndk/ndk/platform/ndk/sources/crystax/bin/gen-bsd-sources  */

/*
 * CrystaX NDK contains code from libc library of FreeBSD project which by-turn contains
 * code from other projects. Also, several another open-source projects used, such as GNU gcc,
 * GNU binutils, LLVM clang, LLVM libc++ etc. To see specific authors and/or licenses, look
 * into appropriate source file. Here is license for those parts which are not derived from
 * any other projects but written by CrystaX .NET.
 *
 * Copyright (c) 2011-2015 CrystaX .NET.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice, this list of
 *       conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright notice, this list
 *       of conditions and the following disclaimer in the documentation and/or other materials
 *       provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY CrystaX .NET ''AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL CrystaX .NET OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those of the
 * authors and should not be interpreted as representing official policies, either expressed
 * or implied, of CrystaX .NET.
 */

#ifndef __CRYSTAX_INCLUDE_407A6774246ECC66422F36B08226911C30D3EF2223C3DEA70AB70F2C96E9F4BF
#define __CRYSTAX_INCLUDE_407A6774246ECC66422F36B08226911C30D3EF2223C3DEA70AB70F2C96E9F4BF

#include <crystax/id.h>
#include <crystax/freebsd.h>
#if __arm__
#include <crystax/freebsd/sys/arm/include/mangled-endian.h>
#elif __aarch64__
#include <crystax/arm64/endian.h>
#elif __mips__ && !__mips64
#include <crystax/freebsd/sys/mips/include/mangled-endian.h>
#elif __mips64
#include <crystax/mips64/endian.h>
#elif __i386__
#include <crystax/freebsd/sys/x86/include/mangled-endian.h>
#elif __x86_64__
#include <crystax/freebsd/sys/x86/include/mangled-endian.h>
#else
#error Not defined for this ABI
#endif

#endif /* __CRYSTAX_INCLUDE_407A6774246ECC66422F36B08226911C30D3EF2223C3DEA70AB70F2C96E9F4BF */
