/* WARNING!!! THIS IS AUTO-GENERATED FILE!!! DO NOT MODIFY IT MANUALLY!!! */
/* GENERATED BY: /home/crystax/work/ndk/ndk/platform/ndk/sources/crystax/bin/gen-bsd-sources  */

/*
 * CrystaX NDK contains code from libc library of FreeBSD project which by-turn contains
 * code from other projects. Also, several another open-source projects used, such as GNU gcc,
 * GNU binutils, LLVM clang, LLVM libc++ etc. To see specific authors and/or licenses, look
 * into appropriate source file. Here is license for those parts which are not derived from
 * any other projects but written by CrystaX .NET.
 *
 * Copyright (c) 2011-2015 CrystaX .NET.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice, this list of
 *       conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright notice, this list
 *       of conditions and the following disclaimer in the documentation and/or other materials
 *       provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY CrystaX .NET ''AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL CrystaX .NET OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those of the
 * authors and should not be interpreted as representing official policies, either expressed
 * or implied, of CrystaX .NET.
 */

#ifndef __CRYSTAX_INCLUDE_C20ECD85F0D6E38B29AA2F0B13C5839948839AC1373E6F5E43435B71768334B6
#define __CRYSTAX_INCLUDE_C20ECD85F0D6E38B29AA2F0B13C5839948839AC1373E6F5E43435B71768334B6

#include <crystax/id.h>
#include <crystax/freebsd.h>

#define __CRYSTAX_COMPLEX_H_INCLUDED 1

#include <crystax/freebsd/include/mangled-complex.h>

__BEGIN_DECLS

long double atan2l(long double v1, long double v2);
long double cargl(long double complex v1);
extern double complex cpow(double complex v1, double complex v2);
extern float complex cpowf(float complex v1, float complex v2);
extern long double complex cpowl(long double complex v1, long double complex v2);
extern double complex clog(double complex v1);
extern float complex clogf(float complex v1);
extern long double complex clogl(long double complex v1);
extern long double complex cacoshl(long double complex v1);
extern long double complex cacosl(long double complex v1);
extern long double complex casinhl(long double complex v1);
extern long double complex casinl(long double complex v1);
extern long double complex catanhl(long double complex v1);
extern long double complex catanl(long double complex v1);
extern long double complex ccoshl(long double complex v1);
extern long double complex ccosl(long double complex v1);
extern long double complex cexpl(long double complex v1);
extern long double complex csinhl(long double complex v1);
extern long double complex csinl(long double complex v1);
extern long double complex ctanhl(long double complex v1);
extern long double complex ctanl(long double complex v1);

__END_DECLS

#endif /* __CRYSTAX_INCLUDE_C20ECD85F0D6E38B29AA2F0B13C5839948839AC1373E6F5E43435B71768334B6 */
